"""
input:
Role Prompting: Tell the LLM it is a professional, empathetic badminton coach.
Context Injection: Pass the user's intended stroke (e.g., "Smash")
and serialize this exact JSON into the prompt string.
output:
Tell the LLM exactly how you want the final response structured
(e.g., Bullet points, encouragement, actionable drill).
"""

import json


def build_prompt(report: dict, action: str) -> str:
    
    report_json = json.dumps(report, ensure_ascii=False, indent=4)
    prompt = f"""
    Role: You are an elite badminton coach and biomechanics expert.

    Context: You are evaluating a player's execution of a specific badminton stroke. 
    You will be provided with the target action and a detailed telemetry report generated by a computer vision pipeline, 
    which includes 3D pose extraction and rule engine logic.

    Target Action: {action}

    Biomechanical Data:
    ```json
    {report_json}
    ``` 
    Task:
    Analyze the data above and provide direct, actionable coaching feedback.
    Please structure your response with:

    Bullet points for key mechanical flaws.

    Actionable drills or step-by-step corrections.

    A brief, encouraging concluding remark.
    
    Keep it concise and professional.
    """
    return prompt


if __name__ == "__main__":
    report:str={'safety_report': {'elbow_hyperextension': {'issue': 'Elbow angle is within safe limits', 'is_safe': True, 'max_elbow_angle': 145.325}, 'shoulder_impingement': {'issue': 'Shoulder angle is within safe limits', 'is_safe': True, 'max_shoulder_angle': 58.387}}, 'technique_report': {'kinetic_chain': {'issue': 'Kinetic chain is not functioning properly', 'is_proper': False, 'idx_shoulder_peak': 21, 'idx_elbow_peak': 11, 'idx_wrist_peak': 8}, 'impact_point': {'issue': 'Arm fully locked at impact, high risk of injury', 'is_optimal': False, 'impact_height': 0.313, 'threshold': 0.318}}}
    print(build_prompt(report,action='high clear'))
